# Generated by Django 4.1.3 on 2022-11-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
