# Generated by Django 4.1.2 on 2022-10-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': True, 'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterField(
            model_name='product',
            name='img_r',
            field=models.ImageField(default='product.jpg', upload_to='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uploaded',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
